rewrite restart_service

diff --git a/files/plugins/restart_service b/files/plugins/restart_service
--- a/files/plugins/restart_service
+++ b/files/plugins/restart_service
@@ -1,38 +1,62 @@
 #!/bin/bash
 
-while getopts "s:t:a:S:" opt
-do
-  case ${opt} in
-    s)
-      service_state=${OPTARG}
-      ;;
-    t)
-      service_state_type=${OPTARG}
-      ;;
-    a)
-      service_attempt=${OPTARG}
-      ;;
-    S)
-      service=${OPTARG}
-      ;;
-  esac
+log_dir="/var/log/icinga2"
+log_file="restart_service.log"
+
+show_help() {
+  echo
+  echo "$0 --state STATE --state-type TYPE --attempt ATTEMPT --service SERVICE"
+  echo
+  echo "restart a service trought icinga2"
+  echo
+  echo "  --state STATE           CRITICAL or WARNING"
+  echo "  --state-type TYPE       SOFT or HARD"
+  echo "  --attempt ATTEMPT       counter for failed checks"
+  echo "  --service SERVICE       name of the service to be restarted"
+  echo ""
+  echo "Example: --state CRITICAL --state-type HARD --attempt 4 --service nginx"
+  echo
+  echo "Example: --state WARNING --state-type SOFT --attempt 4 --service nginx"
+  echo
+}
+
+# process args
+while [ ! -z "$1" ]; do
+    case $1 in
+        -s|--state)      shift; service_state=${1} ;;
+        -t|--state-type) shift; service_state_type=${1} ;;
+        -a|--attempt)    shift; service_attempt=${1} ;;
+        -S|--service)    shift; service=${1} ;;
+        -h|--help)       show_help; exit 1 ;;
+    esac
+    shift
 done
 
 if ( [ -z "${service_state}" ] || [ -z "${service_state_type}" ] || [ -z "${service_attempt}" ] || [ -z "${service}" ] )
 then
-  echo "USAGE: ${0} -s service_state -t service_state_type -a service_attempt -S service"
+  show_help
   [ -z "${service_state}" ] && echo "  missing service_state"
   [ -z "${service_state_type}" ] && echo "  missing service_state_type"
   [ -z "${service_attempt}" ] && echo "  missing service_attempt"
   [ -z "${service}" ] && echo "  missing service"
   exit 3
 else
+  echo "$(date "+%d.%m.%Y %H:%M:%S") ${0}" >> "${log_dir}/${log_file}"
+  echo "$(date "+%d.%m.%Y %H:%M:%S") service_state     : ${service_state}"      >> "${log_dir}/${log_file}"
+  echo "$(date "+%d.%m.%Y %H:%M:%S") service_state_type: ${service_state_type}" >> "${log_dir}/${log_file}"
+  echo "$(date "+%d.%m.%Y %H:%M:%S") service_attempt   : ${service_attempt}"    >> "${log_dir}/${log_file}"
+  echo "$(date "+%d.%m.%Y %H:%M:%S") service           : ${service}"            >> "${log_dir}/${log_file}"
+
   if ( [ "${service_state}" = "CRITICAL" ] && [ "${service_state_type}" = "HARD" ] )
   then
     sudo $(command -v service) ${service} restart
+    result=${?}
+    echo "$(date "+%d.%m.%Y %H:%M:%S") result: ${result}"
   # only restart on the third attempt of a critical event
   elif ( [ "${service_state}" = "CRITICAL" ] && [ "${service_state_type}" = "SOFT" ] && [ ${service_attempt} -eq 2 ] )
   then
     sudo $(command -v service) ${service} restart
+    result=${?}
+    echo "$(date "+%d.%m.%Y %H:%M:%S") result: ${result}"
   fi
 fi
